name: Build Windows Debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    # 1. Instalamos Qt 6.7.3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        cache: 'true'

    # 2. Configuramos CMake en DEBUG
    - name: Configurar CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    # 3. Compilamos en DEBUG
    - name: Compilar
      run: cmake --build build --config Debug

    # ====================================================
    # PASO CLAVE: Windeployqt con BUCLE Y ASTERISCOS (*)
    # ====================================================
    - name: Añadir DLLs (Windeployqt)
      shell: cmd
      # Este comando recorre toda la carpeta 'build' buscando cualquier .exe
      # y le aplica las librerías de Qt (versión Debug)
      run: for /r build %%i in (*.exe) do windeployqt --debug --compiler-runtime --no-translations "%%i"

    # ====================================================
    # PASO DE SUBIDA: Usando Wildcards (**)
    # ====================================================
    - name: Subir Todo (Exe + DLLs)
      uses: actions/upload-artifact@v4
      with:
        name: JtagScanner-Debug
        # Aquí usamos los asteriscos dobles (**) para buscar en cualquier subcarpeta
        path: |
          build/**/*.exe
          build/**/*.dll
          build/**/platforms/
          build/**/styles/
          build/**/iconengines/
          build/**/imageformats/